universe       = vanilla
executable     = run_job.sh
arguments      = $(Process)
log            = outdir/logs/job_$(Process).log
output         = outdir/logs/job_$(Process).out
error          = outdir/logs/job_$(Process).err
transfer_input_files      = /home/divyajyoti.nln/Cardiff_University/Next_gen_detectability/scripts/next_gen_detect/gen_WF_calc_SNR.py, \
                                /home/divyajyoti.nln/Cardiff_University/Next_gen_detectability/scripts/next_gen_detect/conversions.py, \
                                /home/divyajyoti.nln/Cardiff_University/Next_gen_detectability/scripts/next_gen_detect/detectors.py, \
                                /home/divyajyoti.nln/Cardiff_University/Next_gen_detectability/scripts/next_gen_detect/detector_psds.py, \
				/home/divyajyoti.nln/Cardiff_University/Next_gen_detectability/A-sharp-study/gwpopulation/BBH/injections/input_files/1_pop_PLP_spin_prec_z_MD_zmax_6_lmrd_22_corrected_td_part$(Process).h5, \
				/home/divyajyoti.nln/Cardiff_University/Next_gen_detectability/scripts/next_gen_detect/noise_curves.tar.gz, \
				run_job.sh
transfer_output_files = SNR_output_files

request_cpus   = 8
request_memory = 16GB
request_disk   = 4GB
stream_output = True
stream_error = True

notify_user               = divyajyoti.nln@ligo.org
accounting_group          = ligo.dev.o5.cbc.pe.bilby
accounting_group_user     = divyajyoti.nln

+ProjectName      = "A-sharp-study"
requirements = HAS_CVMFS_software_igwn_org == True

# queue 100
queue Process in 9, 52, 78
