universe       = vanilla
executable     = run_job.sh
arguments      = $(i)
log            = outdir2/logs/job_$(i).log
output         = outdir2/logs/job_$(i).out
error          = outdir2/logs/job_$(i).err
transfer_input_files      = /home/divyajyoti.nln/Cardiff_University/Next_gen_detectability/scripts/next_gen_detect/gen_WF_calc_SNR.py, \
                                /home/divyajyoti.nln/Cardiff_University/Next_gen_detectability/scripts/next_gen_detect/conversions.py, \
                                /home/divyajyoti.nln/Cardiff_University/Next_gen_detectability/scripts/next_gen_detect/detectors.py, \
                                /home/divyajyoti.nln/Cardiff_University/Next_gen_detectability/scripts/next_gen_detect/detector_psds.py, \
				/home/divyajyoti.nln/Cardiff_University/Next_gen_detectability/A-sharp-study/gwpopulation/BBH/injections/input_files/1_pop_PLP_spin_prec_z_MD_zmax_6_lmrd_22_corrected_td/1_pop_PLP_spin_prec_z_MD_zmax_6_lmrd_22_corrected_td_part$(i).h5, \
				/home/divyajyoti.nln/Cardiff_University/Next_gen_detectability/scripts/next_gen_detect/noise_curves.tar.gz, \
				run_job.sh
transfer_output_files = SNR_output_files_XPHM
should_transfer_files = YES

request_cpus   = 8
request_memory = 18GB
request_disk   = 4GB
stream_output = True
stream_error = True

notify_user               = divyajyoti.nln@ligo.org
accounting_group          = ligo.dev.o5.cbc.pe.bilby
accounting_group_user     = divyajyoti.nln

+ProjectName      = "A-sharp-study"
requirements = HAS_CVMFS_software_igwn_org == True

queue i from job_ids.txt
